version: '3'
services:
  db:
    image: mariadb:10.6.2
    volumes:
      - db_data:/var/lib/mysql
    ports:
    - "4406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zeapps
      MYSQL_USER: zeapps
      MYSQL_PASSWORD: zeapps
    
  web:
    depends_on:
      - db
    build: .
    volumes:
        - .:/var/www/html
    ports:
      - "8000:80"
    
volumes:
  db_data: {}